version: '3.8'

services:
  ocr_middleware:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - symbiota-network

networks:
  symbiota-network:
    external: true