# MAKE A COPY AND RENAME TO config.yaml AND FILL FIELDS
app_name: 'server name'
display_name: 'api display name'
model_name: 'model name'
server_version: '1.0.0'
api_version: '1.0.0'
host: 127.0.0.1
port: 8000
azure_route: ''
# tentative config options
weight_location: